import java.util.ArrayList;
import java.util.HashMap;

public class Database {

    private ArrayList<Customer> customersList;
    private ArrayList<Vehicle> vehiclesList;
    private HashMap<Integer, Vehicle> rentedVehiclesMap;

    public Database(){
        customersList = new ArrayList<>();
        vehiclesList = new ArrayList<>();
        rentedVehiclesMap = new HashMap<>();
    }

    /**
     * Takes parameters and creates new instance of Customer which is inserted into ArrayList
     * @param firstName
     * @param lastName
     * @param phoneNumber
     * @param email
     */
    public void newCustomer(String firstName, String lastName, int phoneNumber, String email){
        customersList.add(new Customer(firstName, lastName, phoneNumber, email));
    }

    /**
     * Creates new instance of @Car
     * @param make
     * @param model
     * @param registrationPlate
     * @param odometer
     * @param seat
     */
    public void newCar(String make, String model, String registrationPlate, int odometer, int seat){
        vehiclesList.add(new Car(make, model, registrationPlate, odometer, seat));
    }

    /**
     * Create new instance of @Van
     * @param make
     * @param model
     * @param registrationPlate
     * @param odometer
     * @param maximumLoad
     * @param cargoSpace
     */
    public void newVan(String make, String model, String registrationPlate, int odometer, int maximumLoad, double cargoSpace){
        vehiclesList.add(new Van(make, model, registrationPlate, odometer, maximumLoad, cargoSpace));
    }

    /**
     * @param id - Customer id(position in ArrayList)
     * @param vehicle - Instance of vehicle child class
     */
    public void newRent(int id, Vehicle vehicle){
        rentedVehiclesMap.put(id, vehicle);
    }

    /**
     * Fills this.database with Customer instances generated by ChatGPT Mar 23 Version.
     * prompt n.1(
     * I have a method that is called fillCustomerDatabase, inside that method I call these
     * customersList.add(new Customer("John", "Doe", 5551234, "johndoe@email.com"));
     * create 10 more of these customersList.add
     * )
     * prompt n.2(
     * use more of a czech names and czech phone numbers
     * )
     */
    public void fillCustomerDatabase(){
        customersList.add(new Customer("Ondřej", "Novotný", 777123456, "ondrejnovotny@email.com"));
        customersList.add(new Customer("Petra", "Kučerová", 603123456, "petrakucerova@email.com"));
        customersList.add(new Customer("Jakub", "Veselý", 604123456, "jakubvesely@email.com"));
        customersList.add(new Customer("Markéta", "Horáková", 777234567, "marketahorakova@email.com"));
        customersList.add(new Customer("Tomáš", "Kříž", 603234567, "tomaskriz@email.com"));
        customersList.add(new Customer("Simona", "Pospíšilová", 777345678, "simonapospisilova@email.com"));
        customersList.add(new Customer("Matěj", "Malý", 604345678, "matejmaly@email.com"));
        customersList.add(new Customer("Zuzana", "Vlková", 777456789, "zuzanavlkova@email.com"));
        customersList.add(new Customer("Jiří", "Veselý", 603456789, "jirivesely@email.com"));
        customersList.add(new Customer("Martina", "Pokorná", 777567890, "martinapokorna@email.com"));
    }
    /**
     * Fills this.database with Vehicle instances generated by ChatGPT Mar 23 Version.
     * prompt n.1(
     * I have a method that is called fillVehicleDatabase, inside that method I call these
     * vehiclesList.add(new Car("Volkswagen", "Golf", "4S25544", 12301, 4));
     * create 10 more of these vehicleList.add
     * )
     * prompt n.2(
     * use more european cars
     * )
     */
    public void fillVehicleDatabase(){
        vehiclesList.add(new Van("Ford", "Transit", "4T43322", 45798, 1800, 11.5));
        vehiclesList.add(new Van("Mercedes-Benz", "Sprinter", "3M84536", 78901, 2400, 8.0));
        vehiclesList.add(new Van("Ford", "Transit Connect", "8R48322", 34567, 3400, 6.5));
        vehiclesList.add(new Van("Fiat", "Ducato", "7T49764", 56789, 2200, 8.0));
        vehiclesList.add(new Van("Ford", "Transit Custom", "8R48322", 34987, 3200, 6.0));
        vehiclesList.add(new Car("Volkswagen", "Golf", "4S25544", 12301, 4));
        vehiclesList.add(new Car("Audi", "A4", "1H23456", 8030, 4));
        vehiclesList.add(new Car("BMW", "5 Series", "4K56789", 12120, 4));
        vehiclesList.add(new Car("Mercedes-Benz", "C-Class", "3G98765", 11500, 4));
        vehiclesList.add(new Car("Volkswagen", "Passat", "5L34567", 9500, 4));
        vehiclesList.add(new Car("Peugeot", "308", "9R65432", 6022, 4));
        vehiclesList.add(new Car("Renault", "Clio", "2B98765", 4564, 4));
        vehiclesList.add(new Car("Fiat", "500", "7N23456", 3456, 2));
        vehiclesList.add(new Car("Volvo", "XC60", "6M56789", 14259, 4));
    }
//    public Customer findCustomer(String firstName, String lastName){
//        Customer foundCustomer = new Customer();
//        for(Customer c : customersList){
//            if(firstName.equals(c.getFirstName()) && lastName.equals(c.getLastName())){
//                foundCustomer = c;
//            }
//        }
//        return foundCustomer;
//    }

    /**
     * @return ArrayList customersList
     */
    public ArrayList<Customer> getCustomersList() {
        return customersList;
    }
    /**
     * @return ArrayList vehiclesList
     */
    public ArrayList<Vehicle> getVehiclesList(){
        return  vehiclesList;
    }
    /**
     * @return ArrayList rentedVehiclesMap
     */
    public HashMap<Integer, Vehicle> getRentedVehicles() {
        return rentedVehiclesMap;
    }
}
